name: Sync on DOM Cloud

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"commands":["git reset --hard HEAD","git clean -fd","git pull origin main",
            "composer install --no-dev --optimize-autoloader","php artisan migrate --force",
            "php artisan config:clear","php artisan route:clear","php artisan cache:clear",
            "php artisan view:clear","php artisan config:cache","php artisan route:cache"],"wait":1}
          verbose: true

      # - name: Check deployment status
      #   uses: distributhor/workflow-webhook@v3
      #   with:
      #     webhook_url: https://my.domcloud.co/api/githubdeploycheck
      #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      #     webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
